<?php


class shopGlavpunktPluginSettingsAction extends waViewAction
{
    public function execute()
    {
        //parent::execute(); // TODO: Change the autogenerated stub
        $customer_data = array();
        //var_dump("dfgdf");
        $this->view->assign('customer', $customer_data);
    }
}